version: '3.8'
services:
  web:
    build: .
    ports:
      - "5173:5173"
    command: npm run dev
  cypress:
    build: .
    depends_on:
      - web
    command: npm run cypress:run
    environment:
      - CYPRESS_baseUrl=http://web:5173
